### PR TITLE
Improved documentation for ikue

### PR DESCRIPTION
**Pull request by ecstasy2**

### CODE REVIEW

**Comment by pcowgill** [comment]
@ecstasy2 The documentation looks great. I added some grammar suggestions. Should I update the fork first so that the 20dd5e9 doesn't come through as part of this PR?

**Comment by ecstasy2** [comment]
Integrated your grammar comments.
I don't have a preference. I don't mind having the commit showing up.

**Comment by ecstasy2** [comment]
Do you think we can merge this one?

**Comment by pcowgill** [comment]
@ecstasy2 Thanks for integrating those. In the future, let's try to keep unrelated commits in separate pull requests. But yep, you can go ahead and merge this one.

**Pull request merged**
